import { _electron as electron } from 'playwright';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { Manager, updateConfig } from '../core.mjs';
import { portableCodec } from '../portable.mjs';
const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'manager-current-ui-'));
const home = path.join(temp, 'codex'), data = path.join(temp, 'data');
const codec = await portableCodec(data);
const m = new Manager({ codexHome: home, dataDir: data, codec }); await m.init();
const p = { name: 'Current QA', url: 'https://current-ui.example/v1', key: 'fake-current-ui-key', model: 'saved-model', effort: 'high', adapter: 'none' };
await m.save(p); await m.save({ ...p, name: 'Other key', key: 'fake-other-ui-key' });
const id = m.store.profiles[0].id; await m.switchTo(id);
const changed = updateConfig('', { ...p, url: p.url + '/', model: 'externally-selected-model', effort: 'low' });
await fs.writeFile(m.configPath, changed);
const beforeAuth = await fs.readFile(m.authPath, 'utf8');
const env = { ...process.env, CODEX_HOME: home, CODEX_MANAGER_TEST_DATA: data, PORTABLE_EXECUTABLE_DIR: temp };
delete env.ELECTRON_RUN_AS_NODE;
const executable = process.argv[2];
const app = await electron.launch({ ...(executable ? { executablePath: path.resolve(executable), args: [] } : { args: ['.'] }), env });
try {
  const page = await app.firstWindow(), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.waitForFunction(() => document.querySelector('#count').textContent === '2');
  if (await page.locator('#close-guide').isVisible()) await page.locator('#close-guide').click();
  assert.equal(await page.locator('#current-name').textContent(), p.name);
  assert.equal(await page.locator('.profile.active').count(), 1);
  assert.equal(await page.locator('#current-model').textContent(), 'externally-selected-model');
  assert.equal(await fs.readFile(m.configPath, 'utf8'), changed);
  assert.equal(await fs.readFile(m.authPath, 'utf8'), beforeAuth);
  await page.getByRole('button', { name: '同步 API 配置', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#current-model').textContent === 'saved-model');
  assert.equal(await page.getByRole('button', { name: '已配置为当前 API', exact: true }).isDisabled(), true);
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#current-name').textContent === 'Current QA');
  assert.equal(await page.locator('.profile.active').count(), 1);
  assert.ok(!(await page.locator('body').textContent()).includes(p.key));
  assert.deepEqual(errors, []);
  console.log('Current API UI: startup recognition, separate same-URL keys, unchanged credentials and explicit model sync passed');
} finally { await app.close(); await fs.rm(temp, { recursive: true, force: true }); }
