import { _electron as electron } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';

const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'codex-desktop-qa-'));
const home = path.join(temp, 'codex');
await fs.mkdir(home, { recursive: true });
await fs.mkdir(path.join(temp, 'roaming'), { recursive: true });
const original = '# untouched comment\nmodel_provider = "custom"\nmodel = "gpt-6-sol"\nmodel_reasoning_effort = "xhigh"\n[model_providers.custom]\nbase_url = "https://test.example/v1"\n[desktop]\nlocaleOverride = "zh-CN"\n';
await fs.writeFile(path.join(home, 'config.toml'), original);
await fs.writeFile(path.join(home, 'auth.json'), '{"OPENAI_API_KEY":"qa-original-key"}');
const portableDir = path.join(temp, 'portable');
const dataRoot = path.join(portableDir, 'data');
const env = { ...process.env, CODEX_HOME: home, LOCALAPPDATA: path.join(temp, 'local'), APPDATA: path.join(temp, 'roaming'),
  PORTABLE_EXECUTABLE_DIR: portableDir, CODEX_MANAGER_TEST_DATA: dataRoot };
delete env.ELECTRON_RUN_AS_NODE;
for (const name of Object.keys(env)) if (name.toLowerCase() === 'path') delete env[name];
env.Path = `${process.env.SystemRoot}\\System32;${process.env.SystemRoot}\\System32\\WindowsPowerShell\\v1.0;${process.env.SystemRoot}`;
const packagedPath = process.argv[2];
const launchOptions = {
  ...(packagedPath ? { executablePath: path.resolve(packagedPath), args: [] } : { args: ['.'] }),
  env, timeout: 30000,
};
let app = await electron.launch(launchOptions);
const errors = [];
try {
  const page = await app.firstWindow(); page.on('pageerror', e => errors.push(e.message));
  await page.waitForFunction(() => document.querySelector('#count').textContent === '0');
  assert.equal(await page.locator('.profile').count(), 0);
  assert.ok(page.url().startsWith('file:'));
  const security = await app.evaluate(({ BrowserWindow }) => {
    const prefs = BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();
    return { sandbox: prefs.sandbox, contextIsolation: prefs.contextIsolation, nodeIntegration: prefs.nodeIntegration };
  });
  assert.deepEqual(security, { sandbox: true, contextIsolation: true, nodeIntegration: false });
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
  assert.equal((await page.evaluate(() => window.codexManager.request('nonexistent', {}))).error, '不存在的操作。');
  const state = await page.evaluate(() => window.codexManager.request('state'));
  assert.ok(!JSON.stringify(state).includes('qa-original-key'));
  assert.equal(state.monitor.enabled, false);
  assert.equal(await page.locator('#monitor-body').isVisible(), false);
  assert.equal(await page.locator('footer').count(), 0);
  assert.equal(state.dataDir, dataRoot);
  assert.equal(state.cacheDir, path.join(dataRoot, 'cache'));
  assert.equal(await page.locator('#import-legacy').count(), 0);
  assert.equal((await page.evaluate(() => window.codexManager.request('import-legacy', {}))).error, '不存在的操作。');
  await page.locator('#import').click();
  await page.waitForFunction(() => document.querySelector('.profile.active h3')?.textContent === 'test.example');
  await page.locator('#monitor-toggle').check();
  await page.waitForFunction(() => !document.body.classList.contains('busy'));
  assert.equal((await page.evaluate(() => window.codexManager.request('metrics'))).enabled, true);
  await page.locator('#monitor-toggle').uncheck();
  await page.waitForFunction(() => !document.body.classList.contains('busy'));
  assert.equal(await fs.readFile(path.join(home, 'config.toml'), 'utf8'), original);
  await page.locator('#add').click();
  assert.equal(await page.locator('#profile-options').getAttribute('open'), null);
  await page.locator('input[name="name"]').fill('QA API');
  await page.locator('input[name="url"]').fill('https://qa.example/v1');
  await page.locator('input[name="key"]').fill('qa-new-key');
  await page.locator('#profile-form button[type="submit"]').click();
  await page.locator('#editor').waitFor({ state: 'hidden' });
  await page.waitForFunction(() => !document.body.classList.contains('busy'));
  await page.locator('.profile').filter({ has: page.getByRole('heading', { name: 'QA API', exact: true }) }).locator('.switch-button').click();
  await page.waitForFunction(() => document.querySelector('.profile.active h3')?.textContent === 'QA API');
  assert.equal(JSON.parse(await fs.readFile(path.join(home, 'auth.json'), 'utf8')).OPENAI_API_KEY, 'qa-new-key');
  const migrated = dataRoot;
  await page.locator('#settings').click();
  await page.locator('#settings-dialog').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#storage-details').getAttribute('open'), null);
  assert.equal(await page.locator('#choose-data').count(), 0);
  assert.equal(await page.locator('#data-path').inputValue(), migrated);
  await page.locator('#retention-days').selectOption('7');
  await page.locator('#save-settings').click();
  await page.waitForFunction(() => document.querySelector('#settings-notice').textContent === '已保存');
  await page.waitForFunction(() => document.querySelector('#settings-form').getAttribute('aria-busy') !== 'true');
  const diskSettings = JSON.parse(await fs.readFile(path.join(dataRoot, 'settings.json'), 'utf8'));
  assert.equal(diskSettings.retentionDays, 7);
  assert.equal(diskSettings.dataDir, undefined);
  assert.ok(!JSON.stringify(await page.evaluate(() => window.codexManager.request('state'))).includes('qa-new-key'));
  for (const width of [1440, 768, 390]) {
    await page.setViewportSize({ width, height: 850 });
    await fs.mkdir('test-output', { recursive: true });
    await page.screenshot({ path: `test-output/settings-${width}.png`, fullPage: true });
    assert.ok(await page.locator('#settings-dialog').evaluate(node => node.scrollWidth <= node.clientWidth));
    await page.locator('#storage-details summary').click();
    await page.screenshot({ path: `test-output/settings-files-${width}.png`, fullPage: true });
    assert.ok(await page.locator('#settings-dialog').evaluate(node => node.scrollWidth <= node.clientWidth));
    await page.locator('#storage-details summary').click();
  }
  await page.locator('#close-settings').click();
  await page.setViewportSize({ width: 1040, height: 820 });
  await page.locator('#restore').click();
  await page.waitForFunction(() => document.querySelector('#notice').textContent.includes('已撤销'));
  await page.waitForFunction(() => !document.body.classList.contains('busy'));
  assert.equal(await page.locator('.profile.active h3').textContent(), 'test.example');
  assert.equal(await fs.readFile(path.join(home, 'config.toml'), 'utf8'), original);
  const logFiles = await fs.readdir(path.join(migrated, 'logs'));
  const logs = (await Promise.all(logFiles.map(file => fs.readFile(path.join(migrated, 'logs', file), 'utf8')))).join('');
  assert.ok(logs.includes('switch') && logs.includes('restore'));
  assert.ok(!logs.includes('qa-new-key') && !logs.includes('qa-original-key'));
  await fs.mkdir('test-output', { recursive: true });
  await page.screenshot({ path: `test-output/${packagedPath ? 'packaged' : 'desktop'}-window.png`, fullPage: true });
  assert.deepEqual(errors, []);
  await page.locator('#settings').click();
  await page.locator('#settings-dialog').waitFor({ state: 'visible' });
  await page.locator('#logging-enabled').uncheck();
  await page.locator('#save-settings').click();
  await page.waitForFunction(() => document.querySelector('#settings-notice').textContent === '已保存');
  await app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 0 }); });
  await page.locator('#clear-logs').click();
  assert.ok((await fs.readdir(path.join(migrated, 'logs'))).length);
  await app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 1 }); });
  await page.locator('#clear-logs').click();
  await page.waitForFunction(() => document.querySelector('#settings-notice').textContent.includes('已清空'));
  assert.deepEqual(await fs.readdir(path.join(migrated, 'logs')), []);
  await page.locator('#close-settings').click();
  await page.locator('.profile').filter({ has: page.getByRole('heading', { name: 'QA API', exact: true }) }).locator('.switch-button').click();
  await page.waitForFunction(() => document.querySelector('.profile.active h3')?.textContent === 'QA API');
  await page.locator('#monitor-toggle').check();
  await page.waitForFunction(() => !document.body.classList.contains('busy'));
  await fs.appendFile(path.join(home, 'config.toml'), '\n# Codex app changed settings\n');
  await fs.writeFile(path.join(home, 'auth.json'), '{"OPENAI_API_KEY":"manually-updated-key"}');
  await page.locator('#monitor-toggle').uncheck();
  await page.waitForFunction(() => !document.body.classList.contains('busy'));
  assert.equal((await page.evaluate(() => window.codexManager.request('metrics'))).enabled, false);
  assert.equal(JSON.parse(await fs.readFile(path.join(home, 'auth.json'), 'utf8')).OPENAI_API_KEY, 'manually-updated-key');
  assert.ok((await fs.readFile(path.join(home, 'config.toml'), 'utf8')).includes('# Codex app changed settings'));
  const qaProfile = (await page.evaluate(() => window.codexManager.request('state'))).profiles.find(p => p.name === 'QA API');
  assert.equal((await page.evaluate(id => window.codexManager.request('switch', { id }), qaProfile.id)).ok, true);
  await page.evaluate(() => load());
  await page.locator('#monitor-toggle').check();
  await page.waitForFunction(() => !document.body.classList.contains('busy'));
  await fs.appendFile(path.join(home, 'config.toml'), '\n# Codex app changed settings before quit\n');
  await app.close();
  assert.equal(JSON.parse(await fs.readFile(path.join(home, 'auth.json'), 'utf8')).OPENAI_API_KEY, 'qa-new-key');
  assert.ok((await fs.readFile(path.join(home, 'config.toml'), 'utf8')).includes('# Codex app changed settings before quit'));
  const movedDir = path.join(temp, 'another-computer', 'portable'), movedData = path.join(movedDir, 'data');
  await fs.cp(dataRoot, movedData, { recursive: true });
  const newHome = path.join(temp, 'another-computer', 'codex');
  app = await electron.launch({ ...launchOptions, env: { ...env, CODEX_HOME: newHome, PORTABLE_EXECUTABLE_DIR: movedDir, CODEX_MANAGER_TEST_DATA: movedData,
    LOCALAPPDATA: path.join(temp, 'another-computer', 'local'), APPDATA: path.join(temp, 'another-computer', 'roaming') } });
  const restartedPage = await app.firstWindow();
  await restartedPage.waitForFunction(() => document.querySelector('#count').textContent === '2');
  const restartedState = await restartedPage.evaluate(() => window.codexManager.request('state'));
  assert.equal(restartedState.dataDir, movedData);
  assert.equal(restartedState.settings.logging, false);
  assert.equal(restartedState.settings.retentionDays, 7);
  assert.equal(restartedState.canRestore, false);
  assert.deepEqual(await fs.readdir(path.join(movedData, 'logs')), []);
  await assert.rejects(fs.access(path.join(newHome, 'auth.json')), { code: 'ENOENT' });
  await restartedPage.locator('.profile').filter({ has: restartedPage.getByRole('heading', { name: 'QA API', exact: true }) }).locator('.switch-button').click();
  await restartedPage.waitForFunction(() => document.querySelector('.profile.active h3')?.textContent === 'QA API');
  assert.equal(JSON.parse(await fs.readFile(path.join(newHome, 'auth.json'), 'utf8')).OPENAI_API_KEY, 'qa-new-key');
  console.log(`${packagedPath ? 'Packaged' : 'Desktop'} passed: settings/key changes survive monitor disable and quit, portable paths, migration, key reuse, logs and sandbox.`);
} finally { await app.close(); await fs.rm(temp, { recursive: true, force: true }); }
