import { _electron as electron } from 'playwright';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'manager-guide-'));
const env = { ...process.env, CODEX_HOME: path.join(temp, 'codex'), CODEX_MANAGER_TEST_DATA: path.join(temp, 'data'), PORTABLE_EXECUTABLE_DIR: temp };
delete env.ELECTRON_RUN_AS_NODE;
const executable = process.argv[2];
const app = await electron.launch({ ...(executable ? { executablePath: path.resolve(executable), args: [] } : { args: ['.'] }), env });
try {
  const page = await app.firstWindow();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const guide = page.locator('#quick-guide');
  await guide.waitFor({ state: 'visible' });
  assert.equal(await page.locator('#guide-progress').textContent(), '第 1 / 3 步');
  assert.equal(await page.locator('#add').evaluate(n => n.classList.contains('tutorial-target')), true);
  assert.equal(await guide.locator('li').count(), 3);
  await fs.mkdir('test-output', { recursive: true });
  for (const width of [1440, 768, 390]) {
    await page.setViewportSize({ width, height: 850 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.ok(await guide.evaluate(n => n.scrollWidth <= n.clientWidth));
    await page.evaluate(() => Promise.all(document.getAnimations().map(animation => animation.finished.catch(() => {}))));
    const before = await guide.boundingBox();
    await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
    const after = await guide.boundingBox();
    assert.ok(Math.abs(before.y - after.y) < 2);
    assert.ok(after.y >= 0 && after.y + after.height <= 850);
    await page.screenshot({ path: `test-output/guide-floating-${width}.png` });
    await page.evaluate(() => window.scrollTo(0, 0));
  }
  await page.setViewportSize({ width: 1024, height: 850 });
  await fs.mkdir('test-output', { recursive: true });
  await page.screenshot({ path: 'test-output/guide.png' });
  await page.locator('#guide-add').click();
  await page.locator('#editor').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#editor-guide').isVisible(), true);
  await page.locator('#exit-editor-guide').click();
  assert.equal(await guide.isVisible(), false);
  assert.equal(await page.locator('#editor').isVisible(), true);
  assert.equal(await page.locator('#editor-guide').isVisible(), false);
  await page.locator('#cancel-editor').click();
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '0');
  assert.equal(await guide.isVisible(), false);
  await page.locator('#help').click();
  assert.equal(await guide.isVisible(), true);
  await guide.locator('summary').click();
  assert.equal(await guide.locator('details').getAttribute('open'), '');
  await page.locator('#guide-add').click();
  const form = page.locator('#profile-form');
  await form.locator('[name="name"]').fill('Tutorial API');
  await form.locator('[name="url"]').fill('https://tutorial.example/v1');
  await form.locator('[name="key"]').fill('tutorial-fake-key');
  await form.locator('[type="submit"]').click();
  await page.waitForFunction(() => document.querySelector('#guide-progress').textContent === '第 2 / 3 步');
  assert.equal(await page.locator('.switch-button').evaluate(n => n.classList.contains('tutorial-target')), true);
  await page.locator('#guide-add').click();
  await page.waitForFunction(() => document.querySelector('#guide-progress').textContent === '第 3 / 3 步');
  const auth = JSON.parse(await fs.readFile(path.join(temp, 'codex', 'auth.json'), 'utf8'));
  assert.equal(auth.OPENAI_API_KEY, 'tutorial-fake-key');
  assert.equal(await page.locator('#restart-codex').evaluate(n => n.classList.contains('tutorial-target')), true);
  await app.evaluate(({ app, dialog }) => {
    const service = process.mainModule.require(process.mainModule.require('node:path').join(app.getAppPath(), 'desktop', 'restart-codex.cjs'));
    app.guideRestartTest = { response: 0, fail: false, count: 0 };
    service.probe = async () => ({ executable: 'C:\\fake\\Codex.exe', running: true });
    dialog.showMessageBox = async () => ({ response: app.guideRestartTest.response });
    service.restart = async () => { if (app.guideRestartTest.fail) throw new Error('模拟重启失败'); app.guideRestartTest.count++; return { restarted: true }; };
  });
  await page.locator('#restart-codex').click();
  await page.waitForFunction(() => !document.body.classList.contains('busy'));
  assert.equal(await page.locator('#guide-progress').textContent(), '第 3 / 3 步');
  await app.evaluate(({ app }) => { app.guideRestartTest.response = 1; app.guideRestartTest.fail = true; });
  await page.locator('#restart-codex').click();
  await page.waitForFunction(() => document.querySelector('#notice').textContent.includes('模拟重启失败'));
  assert.equal(await page.locator('#guide-progress').textContent(), '第 3 / 3 步');
  await app.evaluate(({ app }) => { app.guideRestartTest.fail = false; });
  await page.locator('#restart-codex').click();
  await page.waitForFunction(() => document.querySelector('#guide-progress').textContent === '已完成');
  assert.equal(await app.evaluate(({ app }) => app.guideRestartTest.count), 1);
  await page.locator('#guide-done').click();
  assert.equal(await page.locator('#help').getAttribute('aria-expanded'), 'false');
  assert.equal(await page.locator('.tutorial-target').count(), 0);
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '1');
  assert.equal(await guide.isVisible(), false);
  await page.locator('#help').click();
  assert.equal(await page.locator('#guide-progress').textContent(), '第 1 / 3 步');
  await page.locator('#close-guide').click();
  assert.equal(await page.locator('.profile').count(), 1);
  assert.deepEqual(errors, []);
  console.log('Interactive tutorial passed: automatic first launch, real save/switch/auth, mocked confirmed restart, cancellation/failure stay on step, exit from editor, persisted dismissal, reopen and responsive layout.');
} finally { await app.close(); await fs.rm(temp, { recursive: true, force: true }); }
