import { _electron as electron } from 'playwright';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'manager-support-ui-'));
const home = path.join(temp, 'codex'), data = path.join(temp, 'data'), output = path.join(temp, 'diagnostic.json');
const env = { ...process.env, CODEX_HOME: home, CODEX_MANAGER_TEST_DATA: data, PORTABLE_EXECUTABLE_DIR: temp };
delete env.ELECTRON_RUN_AS_NODE;
const executable = process.argv[2];
const app = await electron.launch({ ...(executable ? { executablePath: path.resolve(executable), args: [] } : { args: ['.'] }), env });
try {
  const page = await app.firstWindow(), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.waitForFunction(() => document.querySelector('#count').textContent === '0');
  await page.locator('#close-guide').click();
  await app.evaluate(({ app, dialog }, output) => {
    app.supportTest = { calls: 0, response: 0, error: false, saved: false, dialogs: [], restarts: 0, running: true, startedAt: 1 };
    dialog.showMessageBox = async (_window, options) => { app.supportTest.dialogs.push(options); return { response: app.supportTest.response }; };
    dialog.showSaveDialog = async () => app.supportTest.saved ? { filePath: output, canceled: false } : { canceled: true };
    globalThis.fetch = async (url, opts) => {
      if (url !== 'https://support.example/v1/responses' || opts.headers.Authorization !== 'Bearer support-qa-private-key') throw new Error('Wrong test target');
      app.supportTest.calls++;
      if (app.supportTest.error) return Response.json({ error: { message: "The 'qa-model' model is not supported when using Codex with a ChatGPT account. support-qa-private-key", code: 'model_not_found' } }, { status: 400 });
      return new Response('data: {"type":"response.output_text.delta","delta":"private-reply-never-export"}\n\ndata: {"type":"response.completed","response":{"status":"completed"}}\n\n', { headers: { 'Content-Type': 'text/event-stream' } });
    };
    const service = process.mainModule.require(process.mainModule.require('node:path').join(app.getAppPath(), 'desktop', 'restart-codex.cjs'));
    service.probe = async () => ({ executable: 'C:\\fake\\Codex.exe', running: app.supportTest.running, startedAt: app.supportTest.startedAt });
    service.restart = async () => { app.supportTest.restarts++; return { restarted: true }; };
  }, output);
  // Retire the old sticky flag without showing a stale reminder on startup.
  await page.evaluate(() => { localStorage.setItem('restart-needed', '1'); localStorage.removeItem('restart-changed-at'); });
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '0' && localStorage.getItem('restart-needed') === '0');
  assert.equal(await page.locator('#restart-reminder').isVisible(), false);
  const p = { name: 'Support QA', url: 'https://support.example/v1', model: 'qa-model', effort: 'high', adapter: 'none', key: 'support-qa-private-key' };
  assert.equal((await page.evaluate(p => window.codexManager.request('save', p), p)).ok, true);
  await page.evaluate(() => load());
  const testButton = page.getByRole('button', { name: '测试连接 Support QA', exact: true });
  await testButton.click();
  await page.waitForFunction(() => !document.body.classList.contains('busy'));
  assert.equal(await app.evaluate(({ app }) => app.supportTest.calls), 0);
  assert.ok((await app.evaluate(({ app }) => app.supportTest.dialogs[0].detail)).includes('少量用量'));
  await app.evaluate(({ app }) => { app.supportTest.response = 1; });
  await testButton.click();
  await page.waitForFunction(() => document.querySelector('.connection-result strong')?.textContent === '连接成功');
  assert.equal(await app.evaluate(({ app }) => app.supportTest.calls), 1);
  await assert.rejects(fs.access(path.join(home, 'auth.json')), { code: 'ENOENT' });
  await app.evaluate(({ app }) => { app.supportTest.error = true; });
  await testButton.click();
  await page.waitForFunction(() => document.querySelector('.connection-result strong')?.textContent === '模型不可用');
  assert.ok((await page.locator('.connection-result').textContent()).includes('上游模型权限'));
  assert.ok(!(await page.locator('body').textContent()).includes('support-qa-private-key'));
  await page.locator('.switch-button').click();
  await page.locator('#restart-reminder').waitFor({ state: 'visible' });
  const reminder = page.locator('#restart-reminder');
  assert.equal(await reminder.evaluate(n => getComputedStyle(n).position), 'fixed');
  const beforeScroll = await reminder.boundingBox();
  await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
  const afterScroll = await reminder.boundingBox();
  assert.ok(Math.abs(beforeScroll.y - afterScroll.y) < 2);
  await fs.mkdir('test-output', { recursive: true });
  for (const width of [1440, 768, 390]) {
    await page.setViewportSize({ width, height: 850 });
    const box = await reminder.boundingBox();
    assert.ok(box.x >= 0 && box.x + box.width <= width && box.y >= 0 && box.y + box.height <= 850);
    assert.ok(await reminder.evaluate(n => n.scrollWidth <= n.clientWidth));
    await page.screenshot({ path: `test-output/restart-floating-${width}.png` });
  }
  await page.setViewportSize({ width: 1024, height: 850 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.locator('#restore').click();
  await page.waitForFunction(() => document.querySelector('#restart-reminder').hidden && !document.body.classList.contains('busy'));
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '1');
  assert.equal(await reminder.isVisible(), false);
  await assert.rejects(fs.access(path.join(home, 'auth.json')), { code: 'ENOENT' });
  await page.locator('.switch-button').click();
  await reminder.waitFor({ state: 'visible' });
  await page.locator('#restart-later').click();
  assert.equal(await reminder.isVisible(), false);
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '1');
  assert.equal(await page.locator('#restart-reminder').isVisible(), true);
  await app.evaluate(({ app }) => { app.supportTest.response = 0; });
  await page.locator('#restart-now').click();
  await page.waitForFunction(() => !document.body.classList.contains('busy'));
  assert.equal(await page.locator('#restart-reminder').isVisible(), true);
  assert.equal(await app.evaluate(({ app }) => app.supportTest.restarts), 0);
  await app.evaluate(({ app }) => { app.supportTest.response = 1; });
  await page.locator('#restart-now').click();
  await page.waitForFunction(() => document.querySelector('#restart-reminder').hidden);
  assert.equal(await app.evaluate(({ app }) => app.supportTest.restarts), 1);
  await page.locator('#restore').click();
  await reminder.waitFor({ state: 'visible' });
  await page.locator('#help').click();
  assert.equal(await reminder.isVisible(), false);
  await page.locator('#close-guide').click();
  assert.equal(await reminder.isVisible(), true);
  await page.locator('#restart-now').click();
  await page.waitForFunction(() => document.querySelector('#restart-reminder').hidden);
  assert.equal(await app.evaluate(({ app }) => app.supportTest.restarts), 2);
  await page.locator('#settings').click();
  await page.locator('#export-diagnostics').click();
  await page.waitForFunction(() => !document.querySelector('#export-diagnostics').disabled);
  await assert.rejects(fs.access(output), { code: 'ENOENT' });
  await app.evaluate(({ app }) => { app.supportTest.saved = true; });
  await page.locator('#export-diagnostics').click();
  await page.waitForFunction(() => document.querySelector('#settings-notice').textContent.includes('已导出'));
  const raw = await fs.readFile(output, 'utf8');
  for (const secret of ['support-qa-private-key', 'Support QA', p.url, home, data, 'private-reply-never-export']) assert.ok(!raw.includes(secret), secret);
  const report = JSON.parse(raw);
  assert.equal(report.profiles[0].test.kind, 'model'); assert.equal(report.profiles[0].test.httpStatus, 400);
  assert.ok(report.events.some(e => e.operation === 'test-connection' && e.status === 400));
  await page.locator('#close-settings').click();
  await fs.mkdir('test-output', { recursive: true });
  for (const width of [1440, 768, 390]) {
    await page.setViewportSize({ width, height: 850 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.ok(await page.locator('.profile').evaluate(n => n.scrollWidth <= n.clientWidth));
    await page.screenshot({ path: `test-output/support-${width}.png` });
  }
  const id = report.profiles.length ? (await page.evaluate(() => window.codexManager.request('state'))).profiles[0].id : null;
  await page.evaluate(p => window.codexManager.request('save', p), { ...p, id });
  await page.evaluate(() => load());
  assert.equal(await page.locator('.connection-result').count(), 0);
  // Manually restarting outside this tool also clears the persisted reminder.
  await page.locator('.switch-button').click();
  await reminder.waitFor({ state: 'visible' });
  await app.evaluate(({ app }) => { app.supportTest.startedAt = Date.now() + 1000; });
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '1' && localStorage.getItem('restart-needed') === '0');
  assert.equal(await reminder.isVisible(), false);
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#count').textContent === '1');
  assert.equal(await reminder.isVisible(), false);
  // An API switch while Codex is closed requires no restart reminder next launch.
  await app.evaluate(({ app }) => { app.supportTest.running = false; });
  await page.locator('#restore').click();
  await reminder.waitFor({ state: 'visible' });
  await page.reload();
  await page.waitForFunction(() => localStorage.getItem('restart-needed') === '0');
  assert.equal(await reminder.isVisible(), false);
  assert.deepEqual(errors, []);
  console.log('Support desktop passed: paid-test confirmation/cancel, selected API completion/errors, config unchanged by test, persistent restart reminder/cancel/success, sanitized diagnostic export/cancel, edited result invalidation, responsive cards.');
} finally { await app.close(); await fs.rm(temp, { recursive: true, force: true }); }
